adminpanelpart2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [



    path('admin/', admin.site.urls),
    path('', include('application.urls')),
    path('', include('django.contrib.auth.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

application/urls.py
from django.urls import re_path
from django.urls import path
from application import views
from .views import SignUpView

app_name = 'application'
urlpatterns = [

    path('signup/', SignUpView.as_view(), name='signup'),

    path('food_menu/', views.food_menu, name='food_menu'),


    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout1, name='logout'),
    re_path(r'^home/$', views.home, name='home'),

    #path('GeneratePdf/', GeneratePdf.as_view(), name='generatepdf'),
    path('export_pdf/', views.export_pdf, name='exportpdf'),
    path('email_pdf/', views.email_pdf, name='emailpdf'),
    path('email_pdf/', views.movie_list_confirmed, name='movie_list_confirmed'),


    path('movie_list/', views.movie_list, name='movie_list'),
    path('movie/<int:pk>/edit/', views.movie_edit, name='movie_edit'),
    path('movie/<int:pk>/delete/', views.movie_delete, name='movie_delete'),
    path('movie/new/', views.movie_new, name='movie_new'),
    path('accounts/profile/', views.home, name='home'),

    path('theater_list/', views.theater_list, name='theater_list'),
    path('theater/<int:pk>/edit/', views.theater_edit, name='theater_edit'),
    path('theater/<int:pk>/delete/', views.theater_delete, name='theater_delete'),
    path('theater/new/', views.theater_new, name='theater_new'),

    path('ticket_list/', views.ticket_list, name='ticket_list'),
    path('ticket/<int:pk>/edit/', views.ticket_edit, name='ticket_edit'),
    path('ticket/<int:pk>/delete/', views.ticket_delete, name='ticket_delete'),
    path('ticket/new/', views.ticket_new, name='ticket_new'),

    path('showtime_list/', views.showtime_list, name='showtime_list'),
    path('showtime/<int:pk>/edit/', views.showtime_edit, name='showtime_edit'),
    path('showtime/<int:pk>/delete/', views.showtime_delete, name='showtime_delete'),
    path('showtime/new/', views.showtime_new, name='showtime_new'),

    path('food_menu/', views.food_menu, name='food_menu'),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style>
html,body,h1,h2,h3,h4,h5,h6 {font-family: "Roboto", sans-serif;}
.square {
  height: 50px;
  width: 50px;
  background-color: #555;
}
.w3-sidebar {
  z-index: 3;
  width: 250px;
  top: 43px;
  bottom: 0;
  height: inherit;
}
 .logo-image{
    width: 15px;
    height: 10px;
    border-radius: 50%;


}
 .poop-fart{
     margin-right: 10%;
 }

 navbar {
    margin-bottom: 20px;
    border-radius: 0;
}
table {
    background-size: 3096px auto;
    background-repeat: no-repeat;
    background-image: url("https://sherwin.scene7.com/is/image/sw/color-swatch?_tparam_size=250,250&layer=comp&_tparam_color=C6CACA");
}
.center {
  display: block;
  margin-left: auto;
  margin-right: auto;
  width: 50%;
}
.row::after {
  content: "";
  clear: both;
  display: table;
}
.column {
  float: left;
  width: 33.33%;
  padding: 5px;
}
.solid {border-style: solid;}
</style>
<title>SAB Movies</title>
<head>
<!-- Navbar -->

<navbar class="w3-top">

  <div class="w3-bar w3-theme w3-top w3-left-align w3-large">
    <a href="{% url 'application:home' %}">
    <img src="{% static 'sa.png' %}" width="85" height="48" alt="" class="w3-bar-item w3-button w3-hide-small"></a>

    <a href="{% url 'application:movie_list' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Movies</a>
    <a href="{% url 'application:theater_list' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Theaters</a>
    <a href="{% url 'application:showtime_list' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Showtimes</a>
    <a href="{% url 'application:ticket_list' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Tickets</a>
    <a href="{% url 'application:food_menu' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Menu</a>

      {% if user.is_authenticated %}
        <p class="w3-bar-item w3-button w3-hide-small">Username: {{ user.username }}</p>
        <a href="{% url 'application:logout' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-red"> Logout </a>
    {% else %}
      <a href="{% url 'application:login' %}" class="w3-bar-item w3-button w3-hide-small w3-hover-green"> Login </a>


    {% endif %}
    </div>
  </div>
</navbar>
    <br><br><br>
    <title></title>
</head>
   <body>
    {% block content %}

        {% endblock content %}
        <!--Any JS files-->
    </body>
</html>

templates/food_menu.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link href="https://emoji-css.afeld.me/emoji.css" rel="stylesheet">

<link rel="stylesheet" href="https://drive.google.com/uc?export=view&id=1GqWF0CK15cbHa-wkGGZ203LcGt87wqXr">
<section id="popular" class="module">
		<div class="container">

			<div class="row">
				<div class="col-sm-6 col-sm-offset-3">
					<div class="module-header wow fadeInUp animated" style="visibility: visible; animation-name: fadeInUp;">
						<h2 class="module-title">Our New Menu: Coming Soon</h2>
                        <h3 class="module-dark">Our new Trippy Dank Sigma Grindset Grustle Restaurant Opens May 14th.</h3>
						<h4 class="module-subtitle">We have the best food metaphysically possible!!!!</h4>

					</div>
				</div>
			</div>

			<div class="row">

				<div class="col-sm-6">

					<div class="menu">
						<div class="row">
							<div class="col-sm-8">
								<h4 class="menu-title">Protein Shake: Chocolate and <i class="em em-b" aria-role="presentation" aria-label="NEGATIVE SQUARED LATIN CAPITAL LETTER B"></i>anilla</h4>
								<div class="menu-detail">Goat's Milk Derivative Sources</div>
							</div>
							<div class="col-sm-4 menu-price-detail">
								<h4 class="menu-price">$3</h4>
							</div>
						</div>
					</div>

					<div class="menu">
						<div class="row">
							<div class="col-sm-8">
								<h4 class="menu-title">Reign Energy Drink</h4>
								<div class="menu-detail">300mg of caffeine</div>
							</div>
							<div class="col-sm-4 menu-price-detail">
								<h4 class="menu-price">$5</h4>
								<div class="menu-label">RAGE</div>
							</div>
						</div>
					</div>

					<div class="menu">
						<div class="row">
							<div class="col-sm-8">
								<h4 class="menu-title">Bucket of Popcorn</h4>
								<div class="menu-detail">4,000 calories of happiness</div>
							</div>
							<div class="col-sm-4 menu-price-detail">
								<h4 class="menu-price">$24</h4>
							</div>
						</div>
					</div>

					<div class="menu">
						<div class="row">
							<div class="col-sm-8">
								<h4 class="menu-title">Beef Jerky a La Mode</h4>
								<div class="menu-detail">Dried tenderloin atop ice cream</div>
							</div>
							<div class="col-sm-4 menu-price-detail">
								<h4 class="menu-price">$13</h4>
							</div>
						</div>
					</div>

					<div class="menu">
						<div class="row">
							<div class="col-sm-8">
								<h4 class="menu-title">Mom's Moldy Meatloaf</h4>
								<div class="menu-detail">We left it in the trash before serving. Extra tender.<i class="em em-astonished" aria-role="presentation" aria-label="ASTONISHED FACE"></i><i class="em em-astonished" aria-role="presentation" aria-label="ASTONISHED FACE"></i><i class="em em-astonished" aria-role="presentation" aria-label="ASTONISHED FACE"></i></div>
							</div>

							<div class="col-sm-4 menu-price-detail">
								<h4 class="menu-price">$36</h4>
							</div>
						</div>
					</div>

				</div>

				<div class="col-sm-6">

					<div class="menu">
						<div class="row">
							<div class="col-sm-8">
								<h4 class="menu-title">Domestic Beer (bottle)</h4>
								<div class="menu-detail">Various Brands</div>
							</div>
							<div class="col-sm-4 menu-price-detail">
								<h4 class="menu-price">$3-10</h4>
							</div>
						</div>
					</div>

					<div class="menu">
						<div class="row">
							<div class="col-sm-8">
								<h4 class="menu-title">Hot Dogs</h4>
								<div class="menu-detail">A classic!<i class="em em-hamburger" aria-role="presentation" aria-label="HAMBURGER"></i><i class="em em-hamburger" aria-role="presentation" aria-label="HAMBURGER"></i></div>
							</div>
							<div class="col-sm-4 menu-price-detail">
								<h4 class="menu-price">$8</h4>
							</div>
						</div>
					</div>

					<div class="menu">
						<div class="row">
							<div class="col-sm-8">
								<h4 class="menu-title">Bang Energy Drink</h4>
								<div class="menu-detail">Spiked with 800mg of caffeine and Dinitrophenol</div>
							</div>
							<div class="col-sm-4 menu-price-detail">
								<h4 class="menu-price">$5</h4>
								<div class="menu-label">DESTRUCTION</div>
							</div>
						</div>
					</div>

					<div class="menu">
						<div class="row">
							<div class="col-sm-8">
								<h4 class="menu-title">Cheerios with Collector's Spoon</h4>
								<div class="menu-detail">Plain cheerios tee hee</div>
							</div>
							<div class="col-sm-4 menu-price-detail">
								<h4 class="menu-price">$10</h4>
							</div>
						</div>
					</div>

					<div class="menu">
						<div class="row">
							<div class="col-sm-8">
								<h4 class="menu-title">Rumple Minze</h4>
								<div class="menu-detail">100 proof. Best served whilst gaming</div>
							</div>
							<div class="col-sm-4 menu-price-detail">
								<h4 class="menu-price">$1337</h4>
							</div>
						</div>
					</div>

				</div>
			</div>

				</div>

	</section>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- Main content: shift it to the right by 250 pixels when the sidebar is visible -->
<div class="w3-main" style="margin-left:250px">

  <div class="w3-row w3-padding-64">
    <div class="w3-twothird w3-container">
      <h1 class="w3-text-dark-blue">Movies Galore</h1>
      <p>Here at Sigma Alpha Beta Theaters, we strive to give you the absolute best theater experience metaphysically possible with our current knowledge of the universe. Our movies are only the best movies available, no garbage low budget Amaz*n Prime movies here! This is the real deal baby. We pride ourselves with the fact that all of our movies are ethically made where all staff members are paid a living wage and are not forced to live in "working poverty levels". Our theaters are home to technology brought back by a time traveler who spoke to our founder and explained that movie theaters must not become obsolete. This time traveler was also responsible for the $AMC rise. Please let a customer service representative know if you experience any teleportation.</p>


        <img src="https://lh5.googleusercontent.com/p/AF1QipOKm-zvhJ4u2p_eGJbs0AfFEXqYBm2PjgLy3_9d=w203-h152-k-no" class="right-align" width="400" height="300" alt="">
            <img src="https://media-cldnry.s-nbcnews.com/image/upload/t_fit-1500w,f_auto,q_auto:best/newscms/2017_19/1994846/170510-time-travel-mn-1150.jpg" class="left-align" width="400" height="300" alt="">
    </div>
    </div>
  </div>


<script>
// Get the Sidebar
var mySidebar = document.getElementById("mySidebar");

// Get the DIV with overlay effect
var overlayBg = document.getElementById("myOverlay");



</script>
{% endblock %}

templates/movie_export.html
{% block content %}


    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md">
                     <div class="thumbnail">
                                                  <div class="solid">
        <div class="text-dark">
            <div class="caption">

                    <h2 style="padding-inline: 150Px"><b>Movies</b></h2>
                <div class="col-md-4">


                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="panel-body">

    </div>
    <div>
            <table class="table table-bordered">

            <thead>
              <tr class="bg-primary">
                <th>ID</th>
                <th>Name</th>
                <th>Length</th>
                <th>Genre</th>
                <th>Rating</th>
                <th>Date Available</th>

            </tr>
            </thead>
            <tbody>

            {% for movie in movies %}
                <tr>
                    <td>{{ movie.movie_id }}</td>
                    <td>{{ movie.name }}</td>
                    <td>{{ movie.length_min }}</td>
                    <td>{{ movie.genre }}</td>
                    <td>{{ movie.rating }}</td>
                    <td>{{ movie.available_date }}</td>


                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
            </div>
        </div>
        </div>
    </div>
{% endblock %}

templates/movie_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md">
                     <div class="thumbnail">
                                                  <div class="solid">
        <div class="text-dark">
            <div class="caption">

                    <h2 style="padding-inline: 150Px"><b>Movies</b></h2>
                <div class="col-md-4">


                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="panel-body">

    </div>
    <div>
            <table class="table table-bordered">

            <thead>
              <tr class="bg-primary">
                <th>ID</th>
                <th>Name</th>
                <th>Length</th>
                <th>Genre</th>
                <th>Rating</th>
                <th>Date Available</th>
                <th colspan="1">Actions</th>
            </tr>
            </thead>
            <tbody>

            {% for movie in movies %}
                <tr>
                    <td>{{ movie.movie_id }}</td>
                    <td>{{ movie.name }}</td>
                    <td>{{ movie.length_min }}</td>
                    <td>{{ movie.genre }}</td>
                    <td>{{ movie.rating }}</td>
                    <td>{{ movie.available_date }}</td>


                    <td><a href="{% url 'application:movie_edit' pk=movie.pk %}" class="w3-button w3-yellow">Edit</a>
                     <a href="{% url 'application:movie_delete' pk=movie.pk %}"
                           onclick="return confirm('Are you sure you want to delete {{ movie.name }}?')"
                           class="w3-button w3-red">Delete</a>
                    </td>


                </tr>
            {% endfor %}
            </tbody>
        </table>
                    <div class="row">
                 <a href="{% url 'application:movie_new' %}" class="row"><span
                    class="w3-button w3-black">Add Movie</span></a>
     </div>
                    <div class="row">
                        <a href=" {% url 'application:exportpdf' %}" class="w3-button w3-black">Export PDF</a>
                        <a href=" {% url 'application:emailpdf' %}" class="w3-button w3-black">Email PDF</a>

    </div>
            </div>
        </div>
        </div>
    </div>
{% endblock %}

templates/movie_new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
    <h1>Create a New Movie</h1>
    <form method="POST" class="movie-form">{% csrf_token %}
          {{ form|crispy }}
        <br>
        <button type="submit" class="save w3-button w3-black">Save</button>
    </form>
    </div>
{% endblock %}

templates/showtime_delete.html
 {% block body_block %}
    <h1>Delete Showtime{{ showtime.id }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'application:showtime_list' pk=showtime.pk %} ">Cancel</a>
    </form>
{% endblock %}

templates/showtime_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
    <h1>Edit Showtime</h1>
    <form method="POST" class="showtime-form">{% csrf_token %}
         {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
    </div>
{% endblock %}

templates/showtime_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md">
                     <div class="thumbnail">
                                                  <div class="solid">
        <div class="text-dark">
            <div class="caption">

                    <h2 style="padding-inline: 150Px"><b>Showtimes</b></h2>
                <div class="col-md-4">


                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="panel-body">

    </div>
    <div>
            <table class="table table-bordered">

            <thead>
            <tr class="bg-primary">
                <th>ID</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th colspan="2">Actions</th>
            </tr>
            </thead>
            <tbody>

            {% for showtime in showtimes %}
                <tr>
                    <td>{{ showtime.showtime_id }}</td>
                    <td>{{ showtime.start_time }}</td>
                    <td>{{ showtime.end_time }}</td>




                    <td><a href="{% url 'application:showtime_edit' pk=showtime.pk %}" class="w3-button w3-yellow">Edit</a>
                     <a href="{% url 'application:showtime_delete' pk=showtime.pk %}"
                           onclick="return confirm('Are you sure you want to delete {{ showtime.showtime_id }}?')"
                           class="w3-button w3-red">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

                    <div class="row">
                 <a href="{% url 'application:showtime_new' %}" class="row"><span
                    class="w3-button w3-black">Add Showtime</span></a>
     </div>

    </div>
            </div>
        </div>
{% endblock %}

templates/theater_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md">
                     <div class="thumbnail">
                         <div class="solid">

            <div class="caption">

                    <h2 style="padding-inline: 150Px"><b>Theaters</b></h2>
                <div class="col-md-4">


                    </div>
                </div>
            </div>
        </div>
    </div>
            </div>

    <div class="panel-body">

    </div>
    <div>
            <table class="table table-bordered">

            <thead>
            <tr class="bg-primary">
                <th>ID</th>
                <th>Room Number</th>
                <th>Capacity</th>
                <th>Available</th>
                <th colspan="1">Actions</th>
            </tr>
            </thead>
            <tbody>

            {% for theater in theaters %}
                <tr>
                    <td>{{ theater.theater_id }}</td>
                    <td>{{ theater.room_number }}</td>
                    <td>{{ theater.capacity }}</td>
                    <td>{{ theater.available }}</td>

                 <td><a href="{% url 'application:theater_edit' pk=theater.pk %}" class="w3-button w3-yellow">Edit</a>
                     <a href="{% url 'application:theater_delete' pk=theater.pk %}"
                           onclick="return confirm('Are you sure you want to delete Theater {{ theater.theater_id }}?')"
                           class="w3-button w3-red">Delete</a>
                    </td>




                </tr>
            {% endfor %}
            </tbody>
        </table>

                    <div class="row">
                 <a href="{% url 'application:theater_new' %}" class="row"><span
                    class="w3-button w3-black">Add Theater</span></a>
     </div>

    </div>
            </div>
        </div>
{% endblock %}

templates/theater_new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
    <h1>Create a New Theater</h1>
    <form method="POST" class="theater-form">{% csrf_token %}
          {{ form|crispy }}
        <br>
        <button type="submit" class="save w3-button w3-black">Save</button>
    </form>
    </div>
{% endblock %}

templates/ticket_delete.html
 {% block body_block %}
    <h1>Delete {{ ticket.id }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'application:ticket_list' pk=ticket.id %} ">Cancel</a>
    </form>
{% endblock %}

templates/ticket_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md">
                     <div class="thumbnail">
                                                  <div class="solid">
        <div class="text-dark">
            <div class="caption">

                    <h2 style="padding-inline: 150Px"><b>Tickets</b></h2>
                <div class="col-md-4">


                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="panel-body">

    </div>
    <div>
            <table class="table table-bordered">

            <thead>
            <tr class="bg-primary">
                <th>ID</th>
                <th>Price</th>
                <th>Type</th>
                <th>Matinee</th>
                <th>Sold Date</th>
                <th colspan="1">Actions</th>
            </tr>
            </thead>
            <tbody>

            {% for ticket in tickets %}
                <tr>
                    <td>{{ ticket.ticket_id }}</td>
                    <td>{{ ticket.price }}</td>
                    <td>{{ ticket.type }}</td>
                    <td>{{ ticket.matinee }}</td>
                    <td>{{ ticket.sold_date }}</td>

                    <td><a href="{% url 'application:ticket_edit' pk=ticket.pk %}" class="w3-button w3-yellow">Edit</a>
                     <a href="{% url 'application:ticket_delete' pk=ticket.pk %}"
                           onclick="return confirm('Are you sure you want to delete Ticket {{ ticket.ticket_id }}?')"
                           class="w3-button w3-red">Delete</a>
                    </td>







                </tr>
            {% endfor %}
            </tbody>
        </table>

                    <div class="row">
                 <a href="{% url 'application:ticket_new' %}" class="row"><span
                    class="w3-button w3-black">Add Ticket</span></a>
     </div>

    </div>
            </div>
        </div>
{% endblock %}

templates/ticket_new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
    <h1>Create a New Ticket</h1>
    <form method="POST" class="theater-form">{% csrf_token %}
          {{ form|crispy }}
        <br>
        <button type="submit" class="save w3-button w3-black">Save</button>
    </form>
    </div>
{% endblock %}